export const Smileys = [
  //Smiling & Affectionate
  { name: "Grinning Face 笑臉", icon: "😀" },
  { name: "Grinning Face with Big Eyes 大眼睛咧著嘴笑", icon: "😃" },
  { name: "Grinning Face with Smiling Eyes 笑臉和微笑的眼睛", icon: "😄" },
  { name: "Beaming Face with Smiling Eyes 笑容滿面 眼睛微笑", icon: "😁" },
  { name: "Grinning Squinting Face 咧嘴笑瞇著臉", icon: "😆" },
  { name: "Grinning Face with Sweat 滿頭大汗的笑臉 尷尬", icon: "😅" },
  { name: "Rolling on the Floor Laughing 笑得在地上打滾 哭笑", icon: "🤣" },
  { name: "Face with Tears of Joy 滿臉喜悅的淚水 哭笑", icon: "😂" },
  { name: "Slightly Smiling Face 微微微笑的臉", icon: "🙂" },
  { name: "Winking Face 眨眼的臉", icon: "😉" },
  { name: "Smiling Face with Smiling Eyes 微笑的臉和微笑的眼睛", icon: "😊" },
  { name: "Smiling Face with Halo 帶有光環的笑臉 天使", icon: "😇" },
  { name: "Smiling Face with Hearts 笑臉與愛心 暖 ", icon: "🥰" },
  { name: "Smiling Face with Heart-Eyes 愛心型眼睛的笑臉", icon: "😍" },
  { name: "Star-Struck 追星族", icon: "🤩" },
  { name: "Face Blowing a Kiss 臉上飛吻", icon: "😘" },
  { name: "Kissing Face 親吻臉", icon: "😗" },
  { name: "Kissing Face with Closed Eyes 閉著眼睛親吻臉", icon: "😚" },
  { name: "Kissing Face with Smiling Eyes 用微笑的眼睛親吻臉", icon: "😙" },
  { name: "Smirking Face 傻笑臉", icon: "😏" },
  //Tongues, Hands & Accessories
  { name: "Face Savoring Food 品嘗貪吃食物的臉", icon: "😋" },
  { name: "Face with Tongue 吐舌", icon: "😛" },
  { name: "Winking Face with Tongue 眨眼吐舌", icon: "😜" },
  { name: "Zany Face 滑稽的臉", icon: "🤪" },
  { name: "Squinting Face with Tongue 瞇眼吐舌頭", icon: "😝" },
  { name: "Smiling Face with Open Hands 張開雙手的笑臉", icon: "🤗" },
  { name: "Face with Hand Over Mouth 用手摀住嘴巴的臉", icon: "🤭" },
  { name: "Shushing Face 噓臉", icon: "🤫" },
  { name: "Thinking Face 思考臉", icon: "🤔" },
  { name: "Drooling Face 流口水的臉", icon: "🤤" },
  { name: "Cowboy Hat Face 牛仔帽臉", icon: "🤠" },
  { name: "Partying Face 派對臉", icon: "🥳" },
  { name: "Smiling Face with Sunglasses 戴著太陽墨鏡的笑臉", icon: "😎" },
  { name: "Nerd Face 書呆子臉", icon: "🤓" },
  { name: "Face with Monocle 戴單片眼鏡的臉", icon: "🧐" },
  //Neutral & Skeptical
  { name: "Upside-Down Face 顛倒的臉", icon: "🙃" },
  { name: "Zipper-Mouth Face 拉鍊口臉", icon: "🤐" },
  { name: "Face with Raised Eyebrow 揚眉臉", icon: "🤨" },
  { name: "Neutral Face 中性臉", icon: "😐" },
  { name: "Expressionless Face 面無表情", icon: "😑" },
  { name: "Face Without Mouth 有臉無嘴", icon: "😶" },
  { name: "Unamused Face 不高興的臉", icon: "😒" },
  { name: "Face with Rolling Eyes 翻白眼的臉", icon: "🙄" },
  { name: "Grimacing Face 猙獰的臉", icon: "😬" },
  { name: "Lying Face 說謊的臉", icon: "🤥" },
  //Sleepy & Unwell
  { name: "Relieved Face 釋然的臉", icon: "😌" },
  { name: "Pensive Face 沉思的臉", icon: "😔" },
  { name: "Sleepy Face 困倦的臉 打瞌睡", icon: "😪" },
  { name: "Sleeping Face 睡臉 睡覺", icon: "😴" },
  { name: "Face with Medical Mask 戴著醫用口罩的臉", icon: "😷" },
  { name: "Face with Thermometer 面對溫度計", icon: "🤒" },
  { name: "Face with Head-Bandage 臉上纏著頭繃帶", icon: "🤕" },
  { name: "Nauseated Face 噁心的臉", icon: "🤢" },
  { name: "Face Vomiting 嘔吐的臉", icon: "🤮" },
  { name: "Sneezing Face 打噴嚏的臉", icon: "🤧" },
  { name: "Hot Face 熱臉", icon: "🥵" },
  { name: "Cold Face 冰凍的臉 冷", icon: "🥶" },
  { name: "Woozy Face 頭昏眼花的臉 醉", icon: "🥴" },
  { name: "Face with Crossed-Out Eyes 暈眩的臉", icon: "😵" },
  { name: "Exploding Head 爆炸 腦動大開", icon: "🤯" },
  { name: "Yawning Face 打呵欠的臉", icon: "🥱" },
  //Concerned & Negative
  { name: "Confused Face 困惑的臉", icon: "😕" },
  { name: "Worried Face 擔心的臉", icon: "😟" },
  { name: "Slightly Frowning Face 微微皺眉的臉", icon: "🙁" },
  { name: "Frowning Face 皺眉臉", icon: "☹️" },
  { name: "Face with Open Mouth 張開嘴的臉", icon: "😮" },
  { name: "Hushed Face 沉默的臉", icon: "😯" },
  { name: "Astonished Face 驚訝的臉", icon: "😲" },
  { name: "Flushed Face 臉紅的臉", icon: "😳" },
  { name: "Pleading Face 懇求的臉 拜託", icon: "🥺" },
  { name: "Frowning Face with Open Mouth 張開嘴皺著眉頭", icon: "😦" },
  { name: "Anguished Face 痛苦的臉", icon: "😧" },
  { name: "Fearful Face 可怕的臉", icon: "😨" },
  { name: "Anxious Face with Sweat 滿臉焦急滿頭大汗", icon: "😰" },
  { name: "Sad but Relieved Face 悲傷但如釋重負的哭臉", icon: "😥" },
  { name: "Crying Face 哭臉", icon: "😢" },
  { name: "Loudly Crying Face 大聲哭泣的臉", icon: "😭" },
  { name: "Face Screaming in Fear 恐懼尖叫的臉", icon: "😱" },
  { name: "Confounded Face 困惑的臉", icon: "😖" },
  { name: "Persevering Face 堅忍的臉", icon: "😣" },
  { name: "Disappointed Face 失望的臉", icon: "😞" },
  { name: "Downcast Face with Sweat 滿臉汗水低垂的臉", icon: "😓" },
  { name: "Weary Face 疲倦疲憊的臉", icon: "😩" },
  { name: "Tired Face 疲倦疲憊的臉", icon: "😫" },
  { name: "Face with Steam From Nose 鼻子冒著蒸氣的臉", icon: "😤" },
  { name: "Enraged Face 憤怒的臉", icon: "😡" },
  { name: "Angry Face 憤怒的臉", icon: "😠" },
  { name: "Face with Symbols on Mouth 臉上有嘴巴上的符號", icon: "🤬" },
  { name: "Angry Face with Horns 憤怒的臉與角", icon: "👿" },
  //Costume, Creature & Animal
  { name: "Smiling Face with Horns 有角的笑臉", icon: "😈" },
  { name: "Skull 顱骨 骷髏頭", icon: "💀" },
  { name: "Skull and Crossbones 骷髏和交叉骨", icon: "☠️" },
  { name: "Pile of Poo 便便", icon: "💩" },
  { name: "Clown Face 小丑臉", icon: "🤡" },
  { name: "Ogre 食人魔", icon: "👹" },
  { name: "Goblin 哥布林", icon: "👺" },
  { name: "Ghost 鬼", icon: "👻" },
  { name: "Alien 外星人", icon: "👽" },
  { name: "Alien Monster 外星怪物", icon: "👾" },
  { name: "Robot 機器人", icon: "🤖" },
  { name: "Grinning Cat 咧嘴笑的貓", icon: "😺" },
  { name: "Grinning Cat with Smiling Eyes 微笑的貓與微笑的眼睛", icon: "😸" },
  { name: "Cat with Tears of Joy 貓咪流著喜悅的淚水", icon: "😹" },
  { name: "Smiling Cat with Heart-Eyes 心型眼睛的微笑貓", icon: "😻" },
  { name: "Cat with Wry Smile 苦笑的貓", icon: "😼" },
  { name: "Kissing Cat 接吻貓", icon: "😽" },
  { name: "Weary Cat 疲倦的貓", icon: "🙀" },
  { name: "Crying Cat 哭泣的貓", icon: "😿" },
  { name: "Pouting Cat 嘟嘴的貓", icon: "😾" },
  { name: "See-No-Evil Monkey 看不見的猴子", icon: "🙈" },
  { name: "Hear-No-Evil Monkey 聽不見的猴子", icon: "🙉" },
  { name: "Speak-No-Evil Monkey 摀嘴不說話的猴子", icon: "🙊" },
];
